In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [34]:
from Dense import Layer
from Activation import *

In [28]:
-L1_Output, L1_Output

(array([ 1.4843209 , -1.27457787,  0.16531557]),
 array([-1.4843209 ,  1.27457787, -0.16531557]))

In [18]:
X = [[1, 2],
         [2, 4],
         [3, 6],
         [4, 8],
         [5, 10],
         [6, 12]]

In [19]:
L1 = Layer(3, 2)
L1.weights

array([[-0.45777383, -1.01327353],
       [ 0.05403165,  0.11027311],
       [-0.2155336 , -0.47489098]])

In [20]:
L1_Output = L1.forward(X[0])

In [21]:
L1_Output 

array([-1.4843209 ,  1.27457787, -0.16531557])

In [33]:
A = Activation_Sigmoid
A.forward(L1_Output)

array([5.41196823, 1.27954895, 2.17976535])